// ============================================
// MI AI - ZIP Generator
// Creates project files and downloads as ZIP
// By Muaaz Iqbal | Muslim Islam Org
// ============================================

function generateZip() {
  openModal('zip-modal');
}

async function executeZIPGeneration() {
  const description = document.getElementById('zip-description').value.trim();
  const type = document.getElementById('zip-type').value;

  if (!description) {
    showToast('Please describe what to generate', 'error');
    return;
  }

  closeModal();
  hideWelcome();

  const progressId = appendProgressMessage('📦 Generating project files...');

  try {
    const typePrompts = {
      'web': 'Create a complete web app with index.html (2000+ lines), styles.css (1000+ lines), app.js (2000+ lines), README.md',
      'react': 'Create a complete React app with src/App.jsx (2000+ lines), src/components/*.jsx, src/styles/main.css, package.json, README.md',
      'python': 'Create a complete Python project with main.py (2000+ lines), utils.py (1000+ lines), requirements.txt, README.md',
      'nodejs': 'Create a complete Node.js app with src/server.js (2000+ lines), src/routes/*.js, src/models/*.js, package.json, README.md',
      'fullstack': 'Create a complete full-stack app with frontend/index.html, frontend/app.js, backend/server.js (3000+ lines), README.md, package.json',
      'custom': 'Create the requested files with complete, working code'
    };

    updateProgress(progressId, 'Generating code with AI...', 20);

    const aiPrompt = `${typePrompts[type]}

Project description: ${description}

CRITICAL REQUIREMENTS:
1. Write COMPLETE, working code — NO placeholders, NO "..." shortcuts
2. Each file must have 1000-3000+ lines of actual code
3. Include comprehensive comments
4. Add error handling throughout
5. Make it production-ready

Return the response as JSON with this structure:
{
  "projectName": "project-name",
  "files": [
    {
      "name": "filename.ext",
      "path": "relative/path/filename.ext", 
      "content": "complete file content here"
    }
  ]
}
Only return valid JSON, no markdown.`;

    const response = await getQuickResponse(aiPrompt, 'llama-3.3-70b-versatile', SYSTEM_PROMPTS.code);

    updateProgress(progressId, 'Parsing generated files...', 60);

    let projectData;
    try {
      const jsonMatch = response.match(/\{[\s\S]*\}/);
      projectData = jsonMatch ? JSON.parse(jsonMatch[0]) : null;
    } catch {
      // Fallback: create files from markdown code blocks
      projectData = extractFilesFromMarkdown(response, description, type);
    }

    if (!projectData || !projectData.files || projectData.files.length === 0) {
      // Last resort fallback
      projectData = await generateFallbackProject(description, type);
    }

    updateProgress(progressId, 'Creating ZIP archive...', 80);

    // Create ZIP
    const zip = new JSZip();
    const projectName = projectData.projectName || `mi-ai-project-${Date.now()}`;
    const folder = zip.folder(projectName);

    projectData.files.forEach(file => {
      const filePath = file.path || file.name;
      const parts = filePath.split('/');
      if (parts.length > 1) {
        let currentFolder = folder;
        for (let i = 0; i < parts.length - 1; i++) {
          currentFolder = currentFolder.folder(parts[i]);
        }
        currentFolder.file(parts[parts.length - 1], file.content);
      } else {
        folder.file(file.name, file.content);
      }
    });

    // Add MI AI README
    folder.file('MI-AI-INFO.md', `# Generated by MI AI
**Created by:** Muaaz Iqbal | Muslim Islam Org
**Date:** ${new Date().toLocaleString()}
**Project:** ${description}
**Type:** ${type}
**Files:** ${projectData.files.length}

بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ

This project was generated using MI AI powered by Groq.
`);

    updateProgress(progressId, 'Compressing...', 95);

    const content = await zip.generateAsync({
      type: 'blob',
      compression: 'DEFLATE',
      compressionOptions: { level: 9 }
    });

    const url = URL.createObjectURL(content);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${projectName}.zip`;
    a.click();
    URL.revokeObjectURL(url);

    removeProgressMessage(progressId);
    updateProgress(progressId, 'Complete!', 100);

    const fileList = projectData.files.map(f => `• ${f.path || f.name}`).join('\n');
    appendMessage('assistant', `✅ **ZIP Generated: ${projectName}.zip**\n\n**Files created:**\n${fileList}\n\nDownloaded to your device!`, true);
    showToast('ZIP downloaded!', 'success');

  } catch (err) {
    removeProgressMessage(progressId);
    appendMessage('assistant', `❌ ZIP generation failed: ${err.message}`, true);
  }
}

// ---- Extract files from markdown ----
function extractFilesFromMarkdown(text, description, type) {
  const files = [];
  const codeBlockRegex = /```(\w+)?\s*\n([\s\S]*?)```/g;
  const filenameRegex = /(?:File:|Filename:|###)\s*([^\n]+\.[a-z]+)/gi;

  let match;
  let fileIndex = 0;
  const extensions = { web: ['html', 'css', 'js'], react: ['jsx', 'css', 'json'], python: ['py', 'txt'], nodejs: ['js', 'json'] };

  while ((match = codeBlockRegex.exec(text)) !== null) {
    const lang = match[1] || 'txt';
    const content = match[2];
    const ext = { javascript: 'js', python: 'py', typescript: 'ts', html: 'html', css: 'css', json: 'json', bash: 'sh' }[lang] || lang;

    files.push({
      name: `file_${++fileIndex}.${ext}`,
      path: `file_${fileIndex}.${ext}`,
      content
    });
  }

  return {
    projectName: `mi-ai-${type}-${Date.now()}`,
    files: files.length > 0 ? files : [{ name: 'README.md', path: 'README.md', content: text }]
  };
}

// ---- Fallback project ----
async function generateFallbackProject(description, type) {
  const file = await getQuickResponse(
    `Write a complete ${type} implementation for: ${description}
     Write at least 2000 lines of actual working code.
     Include everything needed.`,
    'llama-3.3-70b-versatile',
    SYSTEM_PROMPTS.code
  );

  const ext = { web: 'html', react: 'jsx', python: 'py', nodejs: 'js', fullstack: 'js' }[type] || 'txt';
  return {
    projectName: `mi-ai-${type}`,
    files: [{ name: `main.${ext}`, path: `main.${ext}`, content: file }]
  };
}

// ============================================
// WEB SEARCH
// ============================================

async function webSearch() {
  const query = document.getElementById('message-input').value.trim();
  if (!query) {
    showToast('Enter a search query first', 'error');
    return;
  }
  await performWebSearch(query);
}

async function performWebSearch(query) {
  hideWelcome();
  const thinkEl = appendThinkingMessage(`🔍 Searching: "${query}"...`);

  try {
    // Use DuckDuckGo Instant Answer API (no API key needed)
    const ddgUrl = `https://api.duckduckgo.com/?q=${encodeURIComponent(query)}&format=json&no_html=1&skip_disambig=1`;
    
    // Fallback to Brave Search results display since DuckDuckGo may have CORS issues
    const searchUrl = `https://search.brave.com/search?q=${encodeURIComponent(query)}`;
    
    removeThinkingMessage(thinkEl);

    // Use AI to augment with its knowledge
    const response = await getQuickResponse(
      `The user wants to search for: "${query}"
       Provide comprehensive information about this topic including:
       1. Latest known information
       2. Key facts and data
       3. Important context
       4. Relevant links or resources (if you know them)
       5. Summary and insights
       
       Also provide this search link for live results: ${searchUrl}
       
       Format your response with clear sections and markdown.`,
      'llama-3.3-70b-versatile',
      SYSTEM_PROMPTS.web
    );

    const resultHtml = `
      <div>
        <p>🔍 <strong>Web Search Results: "${query}"</strong></p>
        <div style="display:flex; gap:8px; flex-wrap:wrap; margin:10px 0;">
          <a href="https://search.brave.com/search?q=${encodeURIComponent(query)}" target="_blank" class="download-btn" style="font-size:0.8rem; padding:6px 12px;">
            🦁 Brave Search
          </a>
          <a href="https://www.google.com/search?q=${encodeURIComponent(query)}" target="_blank" class="download-btn" style="font-size:0.8rem; padding:6px 12px; background: linear-gradient(135deg, #4285F4, #34A853);">
            🔍 Google
          </a>
          <a href="https://duckduckgo.com/?q=${encodeURIComponent(query)}" target="_blank" class="download-btn" style="font-size:0.8rem; padding:6px 12px; background: linear-gradient(135deg, #DE5833, #C44B24);">
            🦆 DuckDuckGo
          </a>
        </div>
      </div>
    `;

    appendMessage('assistant', '', true, resultHtml);
    appendMessage('assistant', response, true);

  } catch (err) {
    removeThinkingMessage(thinkEl);
    appendMessage('assistant', `❌ Search failed: ${err.message}`, true);
  }
}

// ============================================
// VOICE HANDLER
// ============================================

let voiceRecognition = null;
let isVoiceActive = false;
let speechSynthesis = window.speechSynthesis;
let currentUtterance = null;

function toggleVoice() {
  if (isVoiceActive) {
    stopVoice();
  } else {
    startVoice();
  }
}

function startVoice() {
  if (!('webkitSpeechRecognition' in window) && !('SpeechRecognition' in window)) {
    showToast('Voice recognition not supported in this browser', 'error');
    return;
  }

  const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
  voiceRecognition = new SpeechRecognition();
  voiceRecognition.continuous = false;
  voiceRecognition.interimResults = true;
  voiceRecognition.lang = 'en-US';

  voiceRecognition.onstart = () => {
    isVoiceActive = true;
    document.getElementById('voice-btn').classList.add('active');
    showVoiceIndicator();
    showToast('🎤 Listening...', 'info');
  };

  voiceRecognition.onresult = (event) => {
    let transcript = '';
    for (let i = event.resultIndex; i < event.results.length; i++) {
      transcript += event.results[i][0].transcript;
    }
    document.getElementById('message-input').value = transcript;
    autoResize(document.getElementById('message-input'));
  };

  voiceRecognition.onend = () => {
    isVoiceActive = false;
    document.getElementById('voice-btn').classList.remove('active');
    hideVoiceIndicator();

    const input = document.getElementById('message-input').value.trim();
    if (input) {
      setTimeout(() => sendMessage(), 500);
    }
  };

  voiceRecognition.onerror = (event) => {
    isVoiceActive = false;
    document.getElementById('voice-btn').classList.remove('active');
    hideVoiceIndicator();
    if (event.error !== 'aborted') {
      showToast('Voice error: ' + event.error, 'error');
    }
  };

  voiceRecognition.start();
}

function stopVoice() {
  if (voiceRecognition) {
    voiceRecognition.stop();
  }
  isVoiceActive = false;
  document.getElementById('voice-btn').classList.remove('active');
  hideVoiceIndicator();
}

function showVoiceIndicator() {
  let indicator = document.getElementById('voice-indicator');
  if (!indicator) {
    indicator = document.createElement('div');
    indicator.id = 'voice-indicator';
    indicator.className = 'voice-indicator';
    indicator.innerHTML = '<div class="voice-pulse"></div><span>🎤 Listening... Speak now</span><button onclick="stopVoice()" style="background:none;border:none;color:var(--accent);cursor:pointer;margin-left:8px;">Stop</button>';
    document.querySelector('.input-area').insertBefore(indicator, document.querySelector('.input-wrapper'));
  }
}

function hideVoiceIndicator() {
  const indicator = document.getElementById('voice-indicator');
  if (indicator) indicator.remove();
}

// Text to Speech
function speakText(text) {
  if (!speechSynthesis) return;

  // Stop current speech
  speechSynthesis.cancel();

  const cleanText = text.replace(/[#*`_\[\]()]/g, '').replace(/\n+/g, ' ').substring(0, 2000);
  currentUtterance = new SpeechSynthesisUtterance(cleanText);
  currentUtterance.rate = 0.9;
  currentUtterance.pitch = 1;
  currentUtterance.volume = 1;

  const voices = speechSynthesis.getVoices();
  const preferredVoice = voices.find(v => v.lang === 'en-US' && v.name.includes('Google')) || 
                          voices.find(v => v.lang === 'en-US') ||
                          voices[0];
  if (preferredVoice) currentUtterance.voice = preferredVoice;

  speechSynthesis.speak(currentUtterance);
}

function stopSpeaking() {
  if (speechSynthesis) speechSynthesis.cancel();
}

// ============================================
// DUAL AI CHAT
// ============================================

async function executeDualAI() {
  const topic = document.getElementById('dual-topic').value.trim();
  const model1 = document.getElementById('dual-model-1').value;
  const model2 = document.getElementById('dual-model-2').value;
  const rounds = parseInt(document.getElementById('dual-rounds').value) || 3;

  if (!topic) {
    showToast('Please enter a debate topic', 'error');
    return;
  }

  closeModal();
  hideWelcome();

  appendMessage('assistant', `🤖🤖 **Dual AI Debate Started!**\n\n**Topic:** ${topic}\n**AI Alpha:** ${GROQ_MODELS[model1]?.name || model1}\n**AI Beta:** ${GROQ_MODELS[model2]?.name || model2}\n**Rounds:** ${rounds}`, true);

  let history1 = [];
  let history2 = [];

  for (let round = 1; round <= rounds; round++) {
    // AI Alpha speaks
    const alpha_thinking = appendThinkingMessage(`🤖 AI Alpha (Round ${round}) is thinking...`);
    
    const alphaPrompt = round === 1 
      ? `You are AI Alpha debating the topic: "${topic}". Present your opening argument in favor of or about this topic. Be comprehensive and persuasive. Previous context: ${history1.slice(-2).map(h=>h.content).join(' | ') || 'None'}`
      : `You are AI Alpha. AI Beta just said: "${history2[history2.length-1]?.content || ''}". Respond to this, defend your position, and advance new arguments about: "${topic}"`;

    const alphaResponse = await getQuickResponse(alphaPrompt, model1, 
      'You are a brilliant debater and thinker. Present comprehensive, well-reasoned arguments.');
    
    history1.push({ role: 'assistant', content: alphaResponse });
    removeThinkingMessage(alpha_thinking);

    // Display dual panels
    const dualHtml = `
      <div class="dual-ai-container">
        <div class="dual-ai-panel">
          <div class="dual-ai-header ai-alpha-header">
            🤖 AI Alpha — Round ${round}
            <small style="margin-left:auto; font-weight:400">${GROQ_MODELS[model1]?.name || model1}</small>
          </div>
          <div class="dual-ai-body">${renderMarkdownSimple(alphaResponse)}</div>
        </div>
      </div>
    `;
    appendMessage('assistant', '', true, dualHtml);

    // AI Beta responds
    const beta_thinking = appendThinkingMessage(`🤖 AI Beta (Round ${round}) is thinking...`);

    const betaPrompt = `You are AI Beta debating with AI Alpha about: "${topic}". 
AI Alpha just said: "${alphaResponse.substring(0, 500)}..."
Present a different perspective, challenge AI Alpha's arguments, and provide your own analysis.
Round: ${round} of ${rounds}`;

    const betaResponse = await getQuickResponse(betaPrompt, model2,
      'You are a brilliant debater. Challenge arguments intelligently and present unique perspectives.');

    history2.push({ role: 'assistant', content: betaResponse });
    removeThinkingMessage(beta_thinking);

    const betaHtml = `
      <div class="dual-ai-container">
        <div class="dual-ai-panel" style="border-color: var(--secondary)">
          <div class="dual-ai-header ai-beta-header">
            🤖 AI Beta — Round ${round}
            <small style="margin-left:auto; font-weight:400">${GROQ_MODELS[model2]?.name || model2}</small>
          </div>
          <div class="dual-ai-body">${renderMarkdownSimple(betaResponse)}</div>
        </div>
      </div>
    `;
    appendMessage('assistant', '', true, betaHtml);

    if (round < rounds) {
      await new Promise(resolve => setTimeout(resolve, 500));
    }
  }

  // Final synthesis
  const synthesis_thinking = appendThinkingMessage('🤖 Generating final synthesis...');
  const synthesis = await getQuickResponse(
    `Provide a balanced synthesis and conclusion for this AI debate about: "${topic}"
     Key points from both sides were discussed.
     Summarize the main arguments, find common ground, and provide a fair conclusion.`,
    'llama-3.3-70b-versatile'
  );
  removeThinkingMessage(synthesis_thinking);
  appendMessage('assistant', `## 🏆 Debate Conclusion\n\n${synthesis}`, true);
}

// Simple markdown renderer
function renderMarkdownSimple(text) {
  return text
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    .replace(/`(.*?)`/g, '<code>$1</code>')
    .replace(/^### (.*$)/gm, '<h4>$1</h4>')
    .replace(/^## (.*$)/gm, '<h3>$1</h3>')
    .replace(/^# (.*$)/gm, '<h2>$1</h2>')
    .replace(/^- (.*$)/gm, '<li>$1</li>')
    .replace(/\n\n/g, '</p><p>')
    .replace(/^/, '<p>')
    .replace(/$/, '</p>');
}

// ============================================
// DATA COLLECTOR
// Learns from user interactions
// ============================================

let userBehaviorData = {
  queries: [],
  preferences: {},
  sessionStart: Date.now(),
  totalMessages: 0,
  preferredModes: {},
  preferredModels: {}
};

function collectUserData(user) {
  if (!user) return;

  // Load existing data
  db.ref(`users/${user.uid}/behavior`).once('value').then(snap => {
    if (snap.exists()) {
      userBehaviorData = { ...userBehaviorData, ...snap.val() };
    }
  });
}

function trackInteraction(type, data) {
  userBehaviorData.totalMessages++;

  if (type === 'mode') {
    userBehaviorData.preferredModes[data] = (userBehaviorData.preferredModes[data] || 0) + 1;
  }
  if (type === 'model') {
    userBehaviorData.preferredModels[data] = (userBehaviorData.preferredModels[data] || 0) + 1;
  }
  if (type === 'query' && data) {
    userBehaviorData.queries.push({
      text: data.substring(0, 100),
      timestamp: Date.now()
    });
    // Keep only last 50 queries
    if (userBehaviorData.queries.length > 50) {
      userBehaviorData.queries = userBehaviorData.queries.slice(-50);
    }
  }

  // Save to Firebase every 5 messages
  if (userBehaviorData.totalMessages % 5 === 0 && currentUser) {
    db.ref(`users/${currentUser.uid}/behavior`).set(userBehaviorData).catch(() => {});
  }
}

// Get personalized suggestions based on behavior
function getPersonalizedSuggestions() {
  const topMode = Object.entries(userBehaviorData.preferredModes)
    .sort(([,a],[,b]) => b - a)[0]?.[0] || 'chat';

  const suggestions = {
    code: ['Debug my Python code', 'Write a REST API in Node.js', 'Create a React component'],
    pdf: ['Generate a book on Machine Learning', 'Create a research paper', 'Write an Islamic book'],
    quran: ['Explain Surah Al-Baqarah', 'Tell me about prayer times', 'Hadith on knowledge'],
    image: ['Generate Islamic geometric art', 'Create a nature landscape', 'Abstract digital art'],
    chat: ['Explain quantum computing', 'Help me plan a project', 'Translate to Arabic']
  };

  return suggestions[topMode] || suggestions.chat;
}
